---
---
- block: 
  - name: Add longhorn Helm repository
    kubernetes.core.helm_repository:
      name: longhorn
      repo_url: https://charts.longhorn.io

  - name: Update Helm repositories
    kubernetes.core.helm_repository:
      name: longhorn
      repo_url: https://charts.longhorn.io/
      force_update: yes
  
  - name: Create longhorn namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: longhorn-system
      state: present
  
  - name: Install gitlab-staging Helm chart
    kubernetes.core.helm:
      name: longhorn
      chart_ref: longhorn/longhorn
      release_namespace: longhorn-system
      values: "{{ longhorn_values }}"
      state: present