gitlab_values:
  global:
    hosts:
      domain: gitlab.local.byrnbaker.me
    edition: ce
  certmanager:
    install: false
  certmanager-issuer:
    email: byrn.baker@gmail.com
  postgresql:
    image:
      tag: 13.6.0
  persistence:
    enabled: true
    gitaly:
      enabled: true
      storageClassName: my-gitaly-storage