gitlab_values:
  global:
    hosts:
      domain: "{{ commonname | replace('*.', '') }}"
      externalIP: 192.168.30.82
    edition: ce
  certmanager:
    install: false
  certmanager-issuer:
    email: "{{ cf_email }}"
  postgresql:
    image:
      tag: 13.6.0
  persistence:
    enabled: true
    gitaly:
      enabled: true
      storageClassName: my-gitaly-storage