staging_gitlab_values:
  global:
    hosts:
      domain: "{{ commonname | replace('*.', '') }}"
    edition: ce
    ingress:
      enabled: true
      provider: traefik
      class: traefik-external
      annotations: 
        kubernetes.io/tls-acme: true
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      configureCertmanager: false

  certmanager:
    install: false
  certmanager-issuer:
    email: "{{ cf_email }}"
  nginx-ingress:
    enabled: false
  postgresql:
    image:
      tag: 13.6.0
  persistence:
    enabled: true
    gitaly:
      enabled: true
      storageClassName: my-gitaly-storage
      
  # CUSTOM - Required for separately managed certmanager
  registry:
    ingress:
      tls:
        secretName: local-byrnbaker-me-staging-tls
  minio:
    ingress:
      tls:
        secretName: local-byrnbaker-me-staging-tls
  gitlab:
    migrations:
      initialRootPassword:
        key: "admin"
    gitlab-pages:
      ingress:
        tls:
          secretName: local-byrnbaker-me-staging-tls
    webservice:
      ingress:
        path: 
        tls:
          secretName: local-byrnbaker-me-staging-tls
    toolbox:
      replicas: 1
      antiAffinityLabels:
        matchLabels:
          app: 'gitaly'

production_gitlab_values:
  global:
    hosts:
      domain: "{{ commonname | replace('*.', '') }}"
    edition: ce
    ingress:
      enabled: true
      provider: traefik
      class: traefik-external
      annotations: 
        kubernetes.io/tls-acme: true
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      configureCertmanager: false
  certmanager:
    install: false
  certmanager-issuer:
    email: "{{ cf_email }}"
  nginx-ingress:
    enabled: false
  postgresql:
    image:
      tag: 13.6.0
  persistence:
    enabled: true
    gitaly:
      enabled: true
      storageClassName: my-gitaly-storage
      
  # CUSTOM - Required for separately managed certmanager
  registry:
    ingress:
      tls:
        secretName: local-byrnbaker-me-tls
  minio:
    ingress:
      tls:
        secretName: local-byrnbaker-me-tls
  gitlab:
    migrations:
      initialRootPassword:
        key: "admin"
    gitlab-pages:
      ingress:
        tls:
          secretName: local-byrnbaker-me-tls
    webservice:
      ingress:
        path: 
        tls:
          secretName: local-byrnbaker-me-tls
    toolbox:
      replicas: 1
      antiAffinityLabels:
        matchLabels:
          app: 'gitaly'