---
- block: 
  - name: Add gitlab Helm repository
    kubernetes.core.helm_repository:
      name: gitlab
      repo_url: https://charts.gitlab.io/

  - name: Update Helm repositories
    kubernetes.core.helm_repository:
      name: gitlab
      repo_url: https://charts.gitlab.io/
      force_update: yes
  
  - name: Create gitlab namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: gitlab
      state: present

  - name: Install gitlab Helm chart
    kubernetes.core.helm:
      name: gitlab
      chart_ref: gitlab/gitlab
      release_namespace: gitlab
      values: "{{ gitlab_values }}"
      state: present
  
  - name: Apply Traefik-Gitlab ingress
    community.kubernetes.k8s:
      state: present
      definition: "{{ lookup('template', 'staging-ingress.j2') }}"
    register: ingress_output