---
- name: Include tasks for each host in k3s_cluster
  include_tasks: destroy_vms.yml
  loop: "{{ groups['k3s_cluster'] }}"
  loop_control:
    loop_var: target_host
  vars:
    host_ip: "{{ hostvars[target_host]['ansible_host'] }}"