---
- block:
    # - name: Create external-ingress namespace
    #   kubernetes.core.k8s:
    #     api_version: v1
    #     kind: Namespace
    #     name: external-ingress
    #     state: present

    - name: Apply default headers
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'reverse-prox-default-headers.j2') }}"
        
    - name: Apply proxmox ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'configmap.j2') }}"