nautobot_values:
  nautobot:
    autoscale:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
    image:
      registry: "ghcr.io"
      repository: "byrn-baker/nautobot-kubernetes"
      tag: "v0.0.4"
      pullSecrets:
        - "ghcr.io"
    replicaCount: 2
    metrics: true
    secretKey: "{{ nb_secretKey }}"
    superUser:
      enabled: true
      username: "{{ nb_username }}"
      password: "{{ nb_password }}"
    extraVars:
      - name: "NAUTOBOT_BANNER_TOP"
        value: "HomeLab"
  workers:
    default:
      replicaCount: 2
  postgresql:
    enabled: true
    auth:
      password: "{{ nb_postgresql_password }}"
  redis:
    enabled: true 
    auth:
      password: "{{ nb_redis_password}}"