nautobot_values:
  nautobot:
    image:
      registry: "ghcr.io"
      repository: "nautobot/nautobot"
      tag: "2.1.5-py3.11" # Latest Version
      pullPolicy: "Always"
    replicaCount: 2
    metrics: true
    secretKey: "{{ nb_secretKey }}"
    superUser:
      enabled: true
      username: "{{ nb_usernam }}"
      password: "{{ nb_password }}"
    extraVars:
      - name: "NAUTOBOT_BANNER_TOP"
        value: "HomeLab"
  workers:
    default:
      replicaCount: 2
  postgresql:
    enabled: true
    auth:
      password: "{{ nb_postgresql_password }}"
  redis:
    enabled: true 
    auth:
      password: "{{ nb_redis_password}}"