---
- name: Add Traefik Helm repository
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Update Helm repositories
  community.kubernetes.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik
    force_update: yes

- name: Create Traefik namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: traefik
    state: present

- name: Get all namespaces
  community.kubernetes.k8s_info:
    kind: Namespace
  register: namespaces

- name: Install Traefik Helm chart
  community.kubernetes.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    values: "{{ traefik_values }}"
    state: present

- name: Get all services
  community.kubernetes.k8s_info:
    kind: Service
    namespace: traefik
  register: services

- name: Get Traefik pods
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: traefik
  register: pods

- name: Apply default headers
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'default-headers.j2') }}"

- name: Get middleware
  community.kubernetes.k8s_info:
    kind: Middleware
    namespace: traefik
  register: middleware

- name: Generate base64-encoded admin password
  shell: htpasswd -nb admin password | openssl base64
  register: base64_password

- debug:
    var: base64_password.stdout

- name: Apply Traefik dashboard secret
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'secret-dashboard.j2') }}"

- name: Get secrets in Traefik namespace
  community.kubernetes.k8s_info:
    kind: Secret
    namespace: traefik
  register: secrets

- name: Apply middleware
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'middleware.j2') }}"

- name: Apply Traefik ingress
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'ingress.j2') }}"